// chair items
const chairItems = [
  {
    id: "1",
    image: './Images/chair image/chair1.jpg" alt="" /',
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "2",
    image: './Images/chair image/chair2.jpg" alt="" /',
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "3",
    image: './Images/chair image/chair3.jpg" alt="" /',
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "4",
    image: './Images/chair image/chair4.jpg" alt="" /',
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "5",
    image: './Images/chair image/chair5.jpg" alt="" /',
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "6",
    image: './Images/chair image/chair6.jpg" alt="" /',
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "7",
    image: './Images/chair image/chair7.jpg" alt="" /',
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "8",
    image: './Images/chair image/chair8.jpg" alt="" /',
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "9",
    image: './Images/chair image/chair9.jpg" alt="" /',
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "10",
    image: './Images/chair image/chair10.jpg" alt="" /',
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "11",
    image: './Images/chair image/chair11.jpg" alt="" /',
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "12",
    image: './Images/chair image/chair22.jpg" alt="" /',
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "13",
    image: './Images/chair image/chair13.jpg" alt="" /',
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "14",
    image: './Images/chair image/chair14.jpg" alt="" /',
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "15",
    image: './Images/chair image/chair15.jpg" alt="" /',
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "16",
    image: './Images/chair image/chair16.jpg" alt="" /',
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "17",
    image: './Images/chair image/chair17.jpg" alt="" /',
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "18",
    image: './Images/chair image/chair18.jpg" alt="" /',
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "19",
    image: './Images/chair image/chair19.jpg" alt="" /',
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "20",
    image: './Images/chair image/chair20.jpg" alt="" /',
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
];

// bed items
const bedItems = [
  {
    id: "1",
    image: './Images/beds image/bed (2).webp" alt="" /',
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "2",
    image: './Images/beds image/bed (3).webp" alt="" /',
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "3",
    image: './Images/beds image/bed (4).webp" alt="" /',
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "4",
    image: './Images/beds image/bed (5).webp" alt="" /',
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "5",
    image: './Images/beds image/bed (6).webp" alt="" /',
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "6",
    image: './Images/beds image/bed (7).webp" alt="" /',
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "7",
    image: './Images/beds image/bed (8).webp" alt="" /',
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "8",
    image: './Images/beds image/bed (9).webp" alt="" /',
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "9",
    image: './Images/beds image/bed (10).webp" alt="" /',
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "10",
    image: './Images/beds image/bed (11).webp" alt="" /',
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "11",
    image: './Images/beds image/bed (12).webp" alt="" /',
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "12",
    image: './Images/beds image/bed (13).webp" alt="" /',
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "13",
    image: './Images/beds image/bed (14).webp" alt="" /',
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "14",
    image: './Images/beds image/bed (15).webp" alt="" /',
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "15",
    image: './Images/beds image/bed (16).webp" alt="" /',
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "16",
    image: './Images/beds image/bed (17).webp" alt="" /',
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
];

// carpet items

const carpetItems = [
  {
    id: "1",
    image: "Images/carpet image/carpet (1).jpeg",
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "2",
    image: "Images/carpet image/carpet (2).PNG",
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "3",
    image: "Images/carpet image/carpet (3).jpeg",
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "4",
    image: "Images/carpet image/carpet (4).JPG",
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "5",
    image: "Images/carpet image/carpet (5).JPG",
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "6",
    image: "Images/carpet image/carpet (6).JPG",
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "7",
    image: "Images/carpet image/carpet (7).JPG",
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "8",
    image: "Images/carpet image/carpet (8).JPG",
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "9",
    image: "Images/carpet image/carpet (9).JPG",
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "10",
    image: "Images/carpet image/carpet (10).JPG",
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "11",
    image: "Images/carpet image/carpet (11).JPG",
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "12",
    image: "Images/carpet image/carpet (8).JPG",
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
];

const sofaItems = [
  {
    id: "1",
    image: "./Images/sofa image/Sofa (1).webp",
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "2",
    image: "./Images/sofa image/Sofa (3).webp",
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "3",
    image: "./Images/sofa image/Sofa (4).webp",
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "4",
    image: "./Images/sofa image/Sofa (5).webp",
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "5",
    image: "./Images/sofa image/Sofa (6).webp",
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "6",
    image: "./Images/sofa image/Sofa (7).webp",
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "7",
    image: "./Images/sofa image/Sofa (8).webp",
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "8",
    image: "./Images/sofa image/Sofa (9).webp",
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "9",
    image: "./Images/sofa image/Sofa (10).webp",
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "10",
    image: "./Images/sofa image/Sofa (11).webp",
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "11",
    image: "./Images/sofa image/Sofa (12).webp",
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "12",
    image: "./Images/sofa image/Sofa (13).webp",
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
];

const feutureItems = [
  {
    id: "1",
    image: "./cupboard.png",
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "2",
    image: "./Images/cupboard.PNG",
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "3",
    image: "./Images/cupboard.PNG",
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "4",
    image: "./Images/cupboard.PNG",
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "5",
    image: "./Images/cupboard.PNG",
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "6",
    image: "./Images/cupboard.PNG",
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "7",
    image: "./Images/cupboard.PNG",
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "8",
    image: "./Images/cupboard.PNG",
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "9",
    image: "./Images/cupboard.PNG",
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "10",
    image: "./Images/cupboard.PNG",
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "11",
    image: "./Images/cupboard.PNG",
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
  {
    id: "12",
    image: "./Images/cupboard.PNG",
    product_brand: "unknoen name",
    product_name: "unknoen name",
    current_price: 1499,
    original_price: 2999,
    discount: 50,
    delivery_date: 10,
  },
];
