// chair products

const chairItems = [
  {
    id: '001',
    item_image: './Images/chair1.jpg',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: 50,
    return_period: 15,
    deliver_date: '14 aug 2025',
   },
   {
    id: '002',
    item_image: './Images/chair2.jpg',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: 50,
    return_period: 15,
    deliver_date: '14 aug 2025',
   },
   {
    id: '003',
    item_image: './Images/chair3.jpg',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: 50,
    return_period: 15,
    deliver_date: '14 aug 2025',
   },
   {
    id: '004',
    item_image: './Images/chair4.jpg',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: 50,
    return_period: 15,
    deliver_date: '14 aug 2025',
   },
   {
    id: '005',
    item_image: './Images/chair5.jpg',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: 50,
    return_period: 15,
    deliver_date: '14 aug 2025',
   },
   {
    id: '006',
    item_image: './Images/chair6.jpg',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: 50,
    return_period: 15,
    deliver_date: '14 aug 2025',
   },
   {
    id: '007',
    item_image: './Images/chair7.jpg',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: 50,
    return_period: 15,
    deliver_date: '14 aug 2025',
   },
   {
    id: '008',
    item_image: './Images/chair8.jpg',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: 50,
    return_period: 15,
    deliver_date: '14 aug 2025',
   },
   {
    id: '009',
    item_image: './Images/chair9.jpg',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: 50,
    return_period: 15,
    deliver_date: '14 aug 2025',
   },
   {
    id: '010',
    item_image: './Images/chair10.jpg',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: 50,
    return_period: 15,
    deliver_date: '14 aug 2025',
   },
   {
    id: '0011',
    item_image: './Images/chair11.jpg',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: 50,
    return_period: 15,
    deliver_date: '14 aug 2025',
   },
   {
    id: '0012',
    item_image: './Images/chair12.jpg',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: 50,
    return_period: 15,
    deliver_date: '14 aug 2025',
   },
   {
    id: '013',
    item_image: './Images/chair13.jpg',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: 50,
    return_period: 15,
    deliver_date: '14 aug 2025',
   },
   {
    id: '014',
    item_image: './Images/chair14.jpg',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: 50,
    return_period: 15,
    deliver_date: '14 aug 2025',
   },
   {
    id: '015',
    item_image: './Images/chair15.jpg',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: 50,
    return_period: 15,
    deliver_date: '14 aug 2025',
   },
   {
    id: '016',
    item_image: './Images/chair16.jpg',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: 50,
    return_period: 15,
    deliver_date: '14 aug 2025',
   },
   {
    id: '017',
    item_image: './Images/chair17.jpg',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: 50,
    return_period: 15,
    deliver_date: '14 aug 2025',
   },
   {
    id: '018',
    item_image: './Images/chair18.jpg',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: 50,
    return_period: 15,
    deliver_date: '14 aug 2025',
   },
   {
    id: '0019',
    item_image: './Images/chair19.jpg',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: 50,
    return_period: 15,
    deliver_date: '14 aug 2025',
   },
   {
    id: '020',
    item_image: './Images/chair20.jpg',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: 50,
    return_period: 15,
    deliver_date: '14 aug 2025',
   },
   {
    id: '021',
    item_image: './Images/chair21.PNG',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: 50,
    return_period: 15,
    deliver_date: '14 aug 2025',
   },
   {
    id: '022',
    item_image: './Images/chair22.jpg',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: 50,
    return_period: 15,
    deliver_date: '14 aug 2025',
   },
   {
    id: '023',
    item_image: './Images/chair23.jpg',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: 50,
    return_period: 15,
    deliver_date: '14 aug 2025',
   },
   {
    id: '024',
    item_image: './Images/chair24.jpg',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: 50,
    return_period: 15,
    deliver_date: '14 aug 2025',
   },
   {
    id: '025',
    item_image: './Images/chair25.jpg',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: 50,
    return_period: 15,
    deliver_date: '14 aug 2025',
   },
   {
    id: '026',
    item_image: './Images/chair26.jpg',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: 50,
    return_period: 15,
    deliver_date: '14 aug 2025',
   },
   {
    id: '027',
    item_image: './Images/chair27.jpg',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: 50,
    return_period: 15,
    deliver_date: '14 aug 2025',
   },
   {
    id: '028',
    item_image: './Images/chair28.jpg',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: 50,
    return_period: 15,
    deliver_date: '14 aug 2025',
   },
   {
    id: '029',
    item_image: './Images/chair29.jpg',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: 50,
    return_period: 15,
    deliver_date: '14 aug 2025',
   },
   {
    id: '030',
    item_image: './Images/chair30.jpg',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: 50,
    return_period: 15,
    deliver_date: '14 aug 2025',
   },
   {
    id: '031',
    item_image: './Images/chair31.jpg',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: 50,
    return_period: 15,
    deliver_date: '14 aug 2025',
   },
   {
    id: '032',
    item_image: './Images/chair32.jpg',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: 50,
    return_period: 15,
    deliver_date: '14 aug 2025',
   },
   {
    id: '033',
    item_image: './Images/chair33.jpg',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: 50,
    return_period: 15,
    deliver_date: '14 aug 2025',
   },
   {
    id: '034',
    item_image: './Images/chair34.jpg',
    company_name: 'unknown company',
    current_price: 1499,
    original_price: 2999,
    discount_price: 50,
    return_period: 15,
    deliver_date: '14 aug 2025',
   },
   {
    id: '035',
    item_image: './Images/chair35.jpg',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: 50,
    return_period: 15,
    deliver_date: '14 aug 2025',
   },
   {
    id: '036',
    item_image: './Images/chair36.jpg',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: 50,
    return_period: 15,
    deliver_date: '14 aug 2025',
   },
   {
    id: '037',
    item_image: './Images/chair37.jpg',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: 50,
    return_period: 15,
    deliver_date: '14 aug 2025',
   },
   {
    id: '038',
    item_image: './Images/chair38.jpg',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: 50,
    return_period: 15,
    deliver_date: '14 aug 2025',
   },
   {
    id: '039',
    item_image: './Images/chair39.jpg',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: 50,
    return_period: 15,
    deliver_date: '14 aug 2025',
   },
   {
    id: '040',
    item_image: './Images/chair40.jpg',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: 50,
    return_period: 15,
    deliver_date: '14 aug 2025',
   },
   {
    id: '041',
    item_image: './Images/chair41.jpg',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: 50,
    return_period: 15,
    deliver_date: '14 aug 2025',
   },
   {
    id: '042',
    item_image: './Images/chair42.jpg',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: 50,
    return_period: 15,
    deliver_date: '14 aug 2025',
   },
   {
    id: '043',
    item_image: './Images/chair43.jpg',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: 50,
    return_period: 15,
    deliver_date: '14 aug 2025',
   },
   {
    id: '044',
    item_image: './Images/chair44.jpg',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: 50,
    return_period: 15,
    deliver_date: '14 aug 2025',
   },
   {
    id: '045',
    item_image: './Images/chair45.jpg',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: 50,
    return_period: 15,
    deliver_date: '14 aug 2025',
   },
   {
    id: '046',
    item_image: './Images/chair46.jpg',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: 50,
    return_period: 15,
    deliver_date: '14 aug 2025',
   },
   {
    id: '047',
    item_image: './Images/chair47.jpg',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: 50,
    return_period: 15,
    deliver_date: '14 aug 2025',
   },
   {
    id: '048',
    item_image: './Images/chair48.jpg',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: 50,
    return_period: 15,
    deliver_date: '14 aug 2025',
   },
 ];

//  sofa products

const sofaItems = [
  {
    id: '001',
    item_image: './Images/Sofa Images/Sofa (1).webp',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: '50%',
    return_days: '10 days',
    delivery: '13 jan 2026',
   },
   {
    id: '2',
    item_image: './Images/Sofa Images/Sofa (49).webp',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: '50%',
   },
   {
    id: '3',
    item_image: './Images/Sofa Images/Sofa (3).webp',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: '50%',
   },
   {
    id: '004',
    item_image: './Images/Sofa Images/Sofa (4).webp',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: '50%',
   },
   {
    id: '005',
    item_image: './Images/Sofa Images/Sofa (5).webp',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: '50%',
   },
   {
    id: '006',
    item_image: './Images/Sofa Images/Sofa (6).webp',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: '50%',
   },
   {
    id: '007',
    item_image: './Images/Sofa Images/Sofa (7).webp',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: '50%',
   },
   {
    id: '008',
    item_image: './Images/Sofa Images/Sofa (8).webp',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: '50%',
   },
   {
    id: '009',
    item_image: './Images/Sofa Images/Sofa (9).webp',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: '50%',
   },
   {
    id: '010',
    item_image: './Images/Sofa Images/Sofa (10).webp',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: '50%',
   },
   {
    id: '011',
    item_image: './Images/Sofa Images/Sofa (11).webp',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: '50%',
   },
   {
    id: '012',
    item_image: './Images/Sofa Images/Sofa (12).webp',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: '50%',
   },
   {
    id: '013',
    item_image: './Images/Sofa Images/Sofa (13).webp',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: '50%',
   },
   {
    id: '014',
    item_image: './Images/Sofa Images/Sofa (14).webp',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: '50%',
   },
   {
    id: '015',
    item_image: './Images/Sofa Images/Sofa (15).webp',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: '50%',
   },
   {
    id: '016',
    item_image: './Images/Sofa Images/Sofa (16).webp',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: '50%',
   },
   {
    id: '017',
    item_image: './Images/Sofa Images/Sofa (17).webp',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: '50%',
   },
   {
    id: '018',
    item_image: './Images/Sofa Images/Sofa (18).webp',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: '50%',
   },
   {
    id: '019',
    item_image: './Images/Sofa Images/Sofa (19).webp',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: '50%',
   },
   {
    id: '020',
    item_image: './Images/Sofa Images/Sofa (20).webp',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: '50%',
   },
   {
    id: '021',
    item_image: './Images/Sofa Images/Sofa (21).webp',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: '50%',
   },
   {
    id: '022',
    item_image: './Images/Sofa Images/Sofa (22).webp',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: '50%',
   },
   {
    id: '023',
    item_image: './Images/Sofa Images/Sofa (23).webp',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: '50%',
   },
   {
    id: '024',
    item_image: './Images/Sofa Images/Sofa (24).webp',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: '50%',
   },
   {
    id: '025',
    item_image: './Images/Sofa Images/Sofa (25).webp',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: '50%',
   },
   {
    id: '026',
    item_image: './Images/Sofa Images/Sofa (26).webp',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: '50%',
   },
   {
    id: '027',
    item_image: './Images/Sofa Images/Sofa (27).webp',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: '50%',
   },
   {
    id: '028',
    item_image: './Images/Sofa Images/Sofa (28).webp',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: '50%',
   },
   {
    id: '029',
    item_image: './Images/Sofa Images/Sofa (29).webp',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: '50%',
   },
   {
    id: '030',
    item_image: './Images/Sofa Images/Sofa (30).webp',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: '50%',
   },
   {
    id: '031',
    item_image: './Images/Sofa Images/Sofa (31).webp',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: '50%',
   },
   {
    id: '032',
    item_image: './Images/Sofa Images/Sofa (32).webp',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: '50%',
   },
   {
    id: '033',
    item_image: './Images/Sofa Images/Sofa (33).webp',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: '50%',
   },
   {
    id: '034',
    item_image: './Images/Sofa Images/Sofa (34).webp',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: '50%',
   },
   {
    id: '035',
    item_image: './Images/Sofa Images/Sofa (35).webp',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: '50%',
   },
   {
    id: '036',
    item_image: './Images/Sofa Images/Sofa (36).webp',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: '50%',
   },
   {
    id: '037',
    item_image: './Images/Sofa Images/Sofa (37).webp',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: '50%',
   },
   {
    id: '038',
    item_image: './Images/Sofa Images/Sofa (38).webp',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: '50%',
   },
   {
    id: '039',
    item_image: './Images/Sofa Images/Sofa (39).webp',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: '50%',
   },
   {
    id: '040',
    item_image: './Images/Sofa Images/Sofa (40).webp',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: '50%',
   },
   {
    id: '041',
    item_image: './Images/Sofa Images/Sofa (41).webp',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: '50%',
   },
   {
    id: '042',
    item_image: './Images/Sofa Images/Sofa (42).webp',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: '50%',
   },
   {
    id: '043',
    item_image: './Images/Sofa Images/Sofa (43).webp',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: '50%',
   },
   {
    id: '044',
    item_image: './Images/Sofa Images/Sofa (44).webp',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: '50%',
   },
   {
    id: '045',
    item_image: './Images/Sofa Images/Sofa (45).webp',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: '50%',
   },
   {
    id: '046',
    item_image: './Images/Sofa Images/Sofa (46).webp',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: '50%',
   },
   {
    id: '047',
    item_image: './Images/Sofa Images/Sofa (47).webp',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: '50%',
   },
   {
    id: '048',
    item_image: './Images/Sofa Images/Sofa (48).webp',
    company_name: 'unknown company',
    item_name: 'sofa chair',
    current_price: 1499,
    original_price: 2999,
    discount_price: '50%',
   },
 ];